sonar.projectKey=nm01n_python-project-52
sonar.organization=nm01n

sonar.sources=task_manager
sonar.tests=task_manager
sonar.test.inclusions=task_manager/tests.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.10

sonar.exclusions=**/migrations/**,**/__pycache__/**,**/fixtures/**
