# Generated by Django 5.2.11 on 2026-03-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0003_label_task_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Name"),
        ),
    ]
